# Generated by Django 2.2.3 on 2020-03-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200319_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='date_created',
            field=models.DateField(default='2020-02-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='ip_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
